In [22]:
import pandas as pd
import numpy as np


### Problem A

System of linear equations is - <br>
$x + y + z + w =250$ <br>
$0.45x  - 0.55y = 0 $ <br>
$y  = 62.5 $ <br>
$0.14 x + 0.2y+0.2z+0.10z =37.5$ <br>



In [23]:
A = np.zeros((4,4))  
b = np.zeros((4,1))


In [24]:
A[0,:] = [1,1,1,1]
A[1,:] = [0.45,-0.55,0,0]
A[2,:] = [0,1,0,0]
A[3,:] = [0.14,0.2,0.2,0.1]
A

array([[ 1.  ,  1.  ,  1.  ,  1.  ],
       [ 0.45, -0.55,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ],
       [ 0.14,  0.2 ,  0.2 ,  0.1 ]])

In [25]:
b[:,0] = [250 , 0, 62.5, 37.5]

In [26]:
np.linalg.solve(A,b)

array([[76.38888889],
       [62.5       ],
       [31.94444444],
       [79.16666667]])

### Problem B

System of linear equations is - 
<br><br>
$r_2-r_1=45  $ <br>
$r_3-r_1=3 $ <br>
$r_4-r_1=31 $ <br>
$r_5-r_1=45  $ <br>
$r_3-r_2=-18 $ <br>
$r_4-r_2=-8 $ <br>
$r_5-r_2=-20  $ <br>
$r_4-r_3=-2 $ <br>
$r_5-r_3=27 $ <br>
$r_5-r_4=38 $ <br>



In [27]:
X = np.zeros((10,5))  
r = np.zeros((5,1))
y = np.zeros((10,1))
X[0,:] = [-1,1,0,0,0]
X[1,:] = [-1,0,1,0,0]
X[2,:] = [-1,0,0,1,0]
X[3,:] = [-1,0,0,0,1]
X[4,:] = [0,-1,1,0,0]
X[5,:] = [0,-1,0,1,0]
X[6,:] = [0,-1,0,0,1]
X[7,:] = [0,0,-1,1,0]
X[8,:] = [0,0,-1,0,1]
X[9,:] = [0,0,0,-1,1]
X

array([[-1.,  1.,  0.,  0.,  0.],
       [-1.,  0.,  1.,  0.,  0.],
       [-1.,  0.,  0.,  1.,  0.],
       [-1.,  0.,  0.,  0.,  1.],
       [ 0., -1.,  1.,  0.,  0.],
       [ 0., -1.,  0.,  1.,  0.],
       [ 0., -1.,  0.,  0.,  1.],
       [ 0.,  0., -1.,  1.,  0.],
       [ 0.,  0., -1.,  0.,  1.],
       [ 0.,  0.,  0., -1.,  1.]])

In [28]:
y[:,0] = [45,3,31,45,-18,-8,-20,-2,27,38]
y

array([[ 45.],
       [  3.],
       [ 31.],
       [ 45.],
       [-18.],
       [ -8.],
       [-20.],
       [ -2.],
       [ 27.],
       [ 38.]])

In [29]:
M = X.transpose()@X
M

array([[ 4., -1., -1., -1., -1.],
       [-1.,  4., -1., -1., -1.],
       [-1., -1.,  4., -1., -1.],
       [-1., -1., -1.,  4., -1.],
       [-1., -1., -1., -1.,  4.]])

In [30]:
RHS = X.transpose()@y
RHS

array([[-124.],
       [  91.],
       [ -40.],
       [ -17.],
       [  90.]])

In [31]:
M[len(M)-1,:] = [1,1,1,1,1]
M

array([[ 4., -1., -1., -1., -1.],
       [-1.,  4., -1., -1., -1.],
       [-1., -1.,  4., -1., -1.],
       [-1., -1., -1.,  4., -1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [32]:
RHS[len(M)-1,] = 0
RHS

array([[-124.],
       [  91.],
       [ -40.],
       [ -17.],
       [   0.]])

In [33]:
np.linalg.solve(M,RHS)

array([[-24.8],
       [ 18.2],
       [ -8. ],
       [ -3.4],
       [ 18. ]])

### Question C

Lehmer matrix of dimension 20




In [34]:
def lehmer_entry(x=20,y=20):
    X = np.zeros((x,y))
    for i in range(x):
        for j in range(y):
            if (j > i):
                X[i,j] = (i+1)/(j+1)
            else :
                X[i,j] = (j+1)/(i+1)
    return(X)


In [35]:
lehmer_entry(x=4,y=4)

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 1.        , 0.66666667, 0.5       ],
       [0.33333333, 0.66666667, 1.        , 0.75      ],
       [0.25      , 0.5       , 0.75      , 1.        ]])

In [36]:
A = lehmer_entry(x=20,y=20)
A

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
        0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ],
       [0.5       , 1.        , 0.66666667, 0.5       , 0.4       ,
        0.33333333, 0.28571429, 0.25      , 0.22222222, 0.2       ,
        0.18181818, 0.16666667, 0.15384615, 0.14285714, 0.13333333,
        0.125     , 0.11764706, 0.11111111, 0.10526316, 0.1       ],
       [0.33333333, 0.66666667, 1.        , 0.75      , 0.6       ,
        0.5       , 0.42857143, 0.375     , 0.33333333, 0.3       ,
        0.27272727, 0.25      , 0.23076923, 0.21428571, 0.2       ,
        0.1875    , 0.17647059, 0.16666667, 0.15789474, 0.15      ],
       [0.25      , 0.5       , 0.75      , 1.        , 0.8       ,
        0.66666667, 0.57142857, 0.5       , 0.44444444, 0.4       ,
        0.36363636, 0.33333333, 0.30769231, 0

### Problem D

In [37]:
C = np.linalg.inv(A)
C

array([[ 1.33333333e+00, -6.66666667e-01, -1.11022302e-16,
         1.48029737e-16,  0.00000000e+00,  7.40148683e-17,
        -2.22044605e-16,  1.48029737e-16, -2.22044605e-16,
         7.40148683e-17, -2.22044605e-16,  7.40148683e-17,
         1.48029737e-16, -1.48029737e-16,  7.40148683e-17,
        -1.35585468e-31,  7.40148683e-17,  5.55111512e-17,
        -1.11022302e-16,  1.48029737e-16],
       [-6.66666667e-01,  2.13333333e+00, -1.20000000e+00,
        -2.50064519e-16, -3.80647894e-17,  2.19929894e-16,
        -4.18712684e-16, -3.27780131e-17,  3.17206578e-16,
        -8.45884209e-18,  2.53765263e-16, -2.11471052e-18,
        -2.45306421e-16, -9.47390314e-16,  2.13585763e-16,
        -6.34413157e-17,  2.54051034e-16, -1.82190445e-16,
         4.44089210e-16, -2.96059473e-16],
       [-1.79606724e-32, -1.20000000e+00,  3.08571429e+00,
        -1.71428571e+00,  1.19904087e-15, -3.61615499e-16,
         5.70971841e-17,  3.61615499e-16, -3.42583105e-16,
        -4.56777473e-16, -3.9

In [38]:
#Given
d = np.array([1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,10 ,9 ,8 ,7 ,6 ,5 ,4 ,3 ,2 ,1])

In [39]:
C.shape

(20, 20)

In [40]:
d.shape

(20,)

In [41]:
RHS_2 = C @ d

In [42]:
np.linalg.solve(A , RHS_2)

array([ 2.96059473e-16, -5.92118946e-15,  1.59872116e-14, -6.90805438e-14,
        1.46908299e-13, -2.27622117e-13,  2.10621264e-13, -3.41060513e-14,
       -2.48120301e+01,  2.00642393e+01,  3.58137507e+01, -3.00626280e+01,
       -3.73699569e-04, -2.77204400e-04, -2.09968770e-04, -1.61954092e-04,
       -1.26922826e-04, -1.00877938e-04,  9.50593309e+01, -1.00062903e+02])