Name : Abhinav Sharma <br>
Eid : ass2575 <br>
Subject : Optimization I <br>


In [10]:
import numpy as np
import gurobipy as gp
import pandas as pd
from matplotlib import pyplot as plt

### Q1


In [14]:
#Load data
dt = pd.read_csv('LinkData_6.csv')
dt.head()

Page0  Page1  Page2  Page3  Page4  Page5  Page6  Page7  Page8  Page9  ...  \
0  False  False  False  False  False  False  False  False  False  False  ...   
1  False  False  False  False  False   True  False  False  False  False  ...   
2   True  False  False  False  False  False  False  False  False  False  ...   
3  False  False  False  False  False  False  False  False  False  False  ...   
4  False  False  False  False  False  False  False  False  False  False  ...   

   Page90  Page91  Page92  Page93  Page94  Page95  Page96  Page97  Page98  \
0   False   False   False   False   False   False   False   False   False   
1   False   False   False   False   False    True   False   False   False   
2   False   False   False   False   False   False   False    True   False   
3   False   False   False   False   False   False   False   False   False   
4   False    True   False   False   False   False   False   False   False   

   Page99  
0   False  
1   False  
2   False  
3   False  
4   False  

[5 rows x 100 columns]

In [13]:
df = np.array(dt)
df

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True, False, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [67]:
#Probab from 17 to 16
round(df[17,16]/sum(df[17,:]),3)

0.048

In [68]:
n = len(df)
n

100

In [69]:
#Initialize
P=np.zeros((n,n))

for i in range(n):
    sum_=sum(df[i,:])
    for j in range(n):
        P[i,j]=df[i,j]/sum_
        


In [70]:
round(sum(P[:,50]),3)

1.163

In [71]:
#Initialize
v=[0.01]*100

v = v @ P

v

array([0.00573833, 0.00769424, 0.00555043, 0.0055146 , 0.00453227,
       0.00557325, 0.0051904 , 0.00556341, 0.00457945, 0.00554611,
       0.00753453, 0.00781997, 0.00757092, 0.00771049, 0.01407555,
       0.01193625, 0.01130167, 0.00886274, 0.00583722, 0.01185877,
       0.00841383, 0.00609158, 0.00880036, 0.00779918, 0.00968227,
       0.0125245 , 0.01052719, 0.0096278 , 0.01128387, 0.01170446,
       0.01019642, 0.00963237, 0.00916069, 0.01089168, 0.01576276,
       0.01121872, 0.01460209, 0.01054923, 0.01640059, 0.01002743,
       0.011999  , 0.01023118, 0.01506729, 0.01101342, 0.01178936,
       0.01551068, 0.01027617, 0.01456252, 0.01014159, 0.01872343,
       0.01162508, 0.01434055, 0.01478432, 0.01454741, 0.01396555,
       0.0092492 , 0.01396915, 0.01273325, 0.01607843, 0.01515518,
       0.0145669 , 0.01379209, 0.00982474, 0.00944187, 0.00992358,
       0.01467456, 0.0158174 , 0.00667514, 0.01539148, 0.01079153,
       0.01045996, 0.00945565, 0.01121931, 0.01151403, 0.00865

In [72]:
round(sum(v[0:25]),3)

0.191

In [73]:
v = [0.01]*100
store = []
for i in range(100):
    v_next = v @ P
    #Put value of v
    v = v_next
    store.append(v.sum())
    
    
store[0:10]

[1.0,
 0.9999999999999999,
 0.9999999999999999,
 0.9999999999999998,
 1.0,
 0.9999999999999999,
 0.9999999999999997,
 0.9999999999999999,
 0.9999999999999998,
 0.9999999999999998]

In [74]:
round(v[60],3)

0.014

In [75]:
v=[0.01]*100

for i in range(500):
    v_next = v @ P
    diff = np.mean( abs(v_next - v))

    if diff < 0.0001:
        print('Error limit reached')
        print(i)
        break
    v = v_next

Error limit reached
3


In [76]:
v

array([0.00429474, 0.00755581, 0.00496142, 0.00395094, 0.00463076,
       0.00490512, 0.00403685, 0.00494001, 0.00534775, 0.00582421,
       0.00792792, 0.00919796, 0.00792954, 0.00780904, 0.01466063,
       0.0125265 , 0.01118054, 0.01020282, 0.00589442, 0.01156642,
       0.00827101, 0.00686881, 0.00931079, 0.00882903, 0.01009723,
       0.01208231, 0.01074875, 0.01092998, 0.00926586, 0.01115431,
       0.01117246, 0.00910644, 0.00919461, 0.00964984, 0.01430459,
       0.00957275, 0.01574659, 0.01130695, 0.01548759, 0.01064109,
       0.01118082, 0.01039511, 0.01417179, 0.0117093 , 0.01241834,
       0.01436138, 0.00971675, 0.01417501, 0.01073215, 0.01823881,
       0.0116464 , 0.01542999, 0.01440859, 0.01410096, 0.01422752,
       0.01053709, 0.01243616, 0.0124304 , 0.01552008, 0.01555809,
       0.01380667, 0.0134601 , 0.01065653, 0.01062133, 0.00930544,
       0.01470236, 0.01577867, 0.00689692, 0.01439863, 0.01090115,
       0.01119421, 0.0086576 , 0.01129441, 0.01261503, 0.00951

In [77]:
#Exract the min
np.argmin(v)

92

### Q2


In [78]:
obj = np.array([13, 15, 20, 5, 16, 0])

# initializing the constraint matrix
ncons = 7
nvar = 6
A = np.zeros((ncons, nvar))                            
b = np.zeros(ncons)
sense = np.array(['<'] * ncons )                     

A[0,] = np.array([1, 1, 1, 1, 1, 0])

#Money - Excess Money  = 100 and excess money = health
A[1,] = np.array([3, 10, 0, 20, 5, -1])

A[2,] = np.array([-0.3, 0.7, 0, 0, 0, 0])

A[3,:3] = np.array([1,2,-1])
#Add in slack var for this
A[3,-1] = 1


A[4,] = np.array([3, 0, 5, 0, 7, 0])

A[5,0] = 1

A[6,] = np.array([2, 5, -2, 7, -3, 1])
            
b = np.array([20, 100, 0, 0, 25, 5, 0])
sense = np.array(['<', '=', '<', '>', '>', '>', '>']) 

for i in range(ncons):
    print(A[i,], sense[i], b[i])

[1. 1. 1. 1. 1. 0.] < 20
[ 3. 10.  0. 20.  5. -1.] = 100
[-0.3  0.7  0.   0.   0.   0. ] < 0
[ 1.  2. -1.  0.  0.  1.] > 0
[3. 0. 5. 0. 7. 0.] > 25
[1. 0. 0. 0. 0. 0.] > 5
[ 2.  5. -2.  7. -3.  1.] > 0


In [79]:
opModel = gp.Model()

opModX = opModel.addMVar(len(obj))

opModCon = opModel.addMConstrs(A, opModX, sense, b)
#No quadratic, linear as obj, no constant
opModel.setMObjective(None, obj, 0, sense=gp.GRB.MAXIMIZE)

opModel.Params.OutputFlag = 0
opModel.optimize()  

#Optimal objective
print(opModel.objVal)


306.4761904761905


In [80]:
print(opModX.x)

print(round(opModX.x[3],2))

[5.         2.14285714 9.28571429 3.04761905 0.52380952 0.        ]
3.05


In [81]:
opModX.SAObjUp[2]

20.400000000000002

In [82]:
#Shadow Prices
[con.Pi for con in opModCon]

[19.666666666666668,
 -0.7333333333333333,
 4.761904761904756,
 -0.33333333333333215,
 0.0,
 -2.70476190476191,
 0.0]

In [83]:
[(con.SARHSLow, con.SARHSUp) for con in opModCon]

[(19.607142857142854, 23.45864661654135),
 (67.14285714285717, 107.85714285714289),
 (-1.15, 0.11000000000000044),
 (-0.39285714285714446, 5.054945054945054),
 (-inf, 65.0952380952381),
 (3.662790697674419, 5.134474327628363),
 (-inf, 21.904761904761898)]