In [1]:
#Import py libraries
import pandas as pd
import numpy as np
import math
import gurobipy as gp

Q2 : Factory Warehouse

In [2]:
#Initialize optimization problem
nvar = 4
ncons = 3
objective = np.array([9, 5, 6, 4])
A_mat = np.zeros((ncons,nvar))
objective

array([9, 5, 6, 4])

In [3]:
b_vec = [11, 1, 1]

In [4]:
sense_vec = np.array(['<', '>', '<']) 

In [5]:
#Quick Check 1
len(objective) == nvar and len(b_vec) == ncons and len(sense_vec) == ncons

True

In [6]:
A_mat[0,:] = [6, 3, 5, 2]
A_mat[1,:] = [0, 0, 1, 1]
A_mat[2,:] = [1, 1, 0, 0]

In [7]:
for i in range(len(A_mat)):
    print(A_mat[i,:]  , sense_vec[i]  , b_vec[i])

[6. 3. 5. 2.] < 11
[0. 0. 1. 1.] > 1
[1. 1. 0. 0.] < 1


In [8]:
#Gurobi
Mod = gp.Model()
Mod_x = Mod.addMVar(len(objective),vtype=['B']*len(objective))
Mod_con = Mod.addMConstrs(A_mat, Mod_x, sense_vec, b_vec)
Mod.setMObjective(None,objective,0,sense=gp.GRB.MAXIMIZE)
Mod.Params.OutputFlag = 0 
Mod.optimize()

Restricted license - for non-production use only - expires 2022-01-13


In [9]:
print(A_mat[])

SyntaxError: invalid syntax (<ipython-input-9-4dea55c81c07>, line 1)

In [10]:
print(Mod.objval , Mod_x.x, Mod_x.x @ A_mat[0,:] )

15.0 [0. 1. 1. 1.] 10.0


Q3 : Western Airlines

In [104]:
#Initialize optimization problem
nvar = 12
ncons = 12
objective = np.array([1]*12)
A_mat = np.zeros((ncons,nvar))
objective

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [105]:
b_vec = [1]*12

In [106]:
sense_vec = np.array(['>']*12) 

In [107]:
#Quick Check 1
len(objective) == nvar and len(b_vec) == ncons and len(sense_vec) == ncons

True

In [108]:
A_mat[0,[0,2,4,6,7,8]] = 1
A_mat[1,[1,7,8]] = 1
A_mat[2,[0,2,6,7,8]] = 1
A_mat[3,[3,9]] = 1
A_mat[4,[0,4,6]] = 1
A_mat[5,[5,9,10]] = 1
A_mat[6,[0,2,4,6]] = 1
A_mat[7,[0,1,2,7,8]] = 1
A_mat[8,[0,1,2,7,8]] = 1
A_mat[9,[3,5,9,10,11]] = 1
A_mat[10,[5,9,10,11]] = 1
A_mat[11,[9,10,11]] = 1

In [109]:
for i in range(len(A_mat)):
    print(A_mat[i,:]  , sense_vec[i]  , b_vec[i])

[1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0.] > 1
[0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.] > 1
[1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0.] > 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.] > 1
[1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.] > 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.] > 1
[1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0.] > 1
[1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0.] > 1
[1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0.] > 1
[0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1.] > 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1.] > 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.] > 1


In [112]:
#Gurobi
Mod = gp.Model()
Mod_x = Mod.addMVar(len(objective),vtype=['B']*len(objective))
Mod_con = Mod.addMConstrs(A_mat, Mod_x, sense_vec, b_vec)
Mod.setMObjective(None,objective,0,sense=gp.GRB.MINIMIZE)
Mod.Params.OutputFlag = 0 
Mod.optimize()

In [113]:
print(Mod.objval , Mod_x.x )

3.0 [1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]


Q4 : Paper Mills
Total numbers of patterns to get 120
- 4 x 25
- 3 x 25, 1 x 37
- 2 x 25, 1 x 54
- 2 x 25, 1 x 37
- 1 x 25, 2 x 37
- 1 x 25, 1 x 37, 1 x 54
- 0 x 25, 0 x 37, 2 x 54
- 0 x 25, 3 x 37, 0 x 54


Detailed combinatorials for sense check
- 4,0,0
- 3,0,0
- 3,1,0
- 2,0,0
- 2,1,0
- 2,0,1
- 2,2,0
- 1,0,0
- 1,0,1
- 1,1,0
- 1,1,1
- 1,2,0
- 0,0,1
- 0,1,0
- 0,2,0
- 0,0,2
- 0,3,0




In [73]:
#Initialize optimization problem
nvar = 8
ncons = 3
objective = np.array([1]*nvar)
A_mat = np.zeros((ncons,nvar))
objective

array([1, 1, 1, 1, 1, 1, 1, 1])

In [74]:
b_vec = [233,148,106]

In [75]:
sense_vec = np.array(['>']*ncons) 

In [76]:
#Quick Check 1
len(objective) == nvar and len(b_vec) == ncons and len(sense_vec) == ncons

True

In [77]:
A_mat[0,:] = [4,3,2,2,1,1,0,0]
A_mat[1,:] = [0,1,0,1,2,1,0,3]
A_mat[2,:] = [0,0,1,0,0,1,2,0]
# A_mat[0,:] = [4,3,3,2,2,2,2,1,1,1,1,1,0,0,0,0,0]
# A_mat[1,:] = [0,0,1,0,1,0,2,0,0,1,1,2,0,1,2,0,3]
# A_mat[2,:] = [0,0,0,0,0,1,0,0,1,0,1,0,1,0,0,2,0]

In [78]:
for i in range(len(A_mat)):
    print(A_mat[i,:]  , sense_vec[i]  , b_vec[i])

[4. 3. 2. 2. 1. 1. 0. 0.] > 233
[0. 1. 0. 1. 2. 1. 0. 3.] > 148
[0. 0. 1. 0. 0. 1. 2. 0.] > 106


In [81]:
#Gurobi
Mod = gp.Model()
Mod_x = Mod.addMVar(len(objective),vtype=['I']*len(objective))
Mod_con = Mod.addMConstrs(A_mat, Mod_x, sense_vec, b_vec)
Mod.setMObjective(None,objective,0,sense=gp.GRB.MINIMIZE)
Mod.Params.OutputFlag = 0 
Mod.optimize()

In [82]:
print(Mod.objval , Mod_x.x )

149.0 [  1.  42.  -0.  -0.  -0. 106.  -0.  -0.]


Q5 : Days off scheduling

Minimize the cost of assigning workers to a 7-day cyclic schedule so that
1) Sufficient workers are available every day.

2) Each person works 5 consecutive days and is idle to the remaining 2 days.

In [87]:
#Initialize optimization problem
nvar = 7
ncons = 7
objective = np.array([330,300,330,360,360,360,360])
A_mat = np.zeros((ncons,nvar))
objective

array([330, 300, 330, 360, 360, 360, 360])

In [88]:
b_vec = [5,13,12,10,14,8,6]

In [89]:
sense_vec = np.array(['>']*ncons) 

In [90]:
#Quick Check 1
len(objective) == nvar and len(b_vec) == ncons and len(sense_vec) == ncons

True

In [96]:
A_mat[0,:] = [1]*5+[0]*2
A_mat[1,:] = [0]*1+[1]*5+[0]*1
A_mat[2,:] = [0]*2+[1]*5
A_mat[3,:] = [1]*1+[0]*2+[1]*4
A_mat[4,:] = [1]*2+[0]*2+[1]*3
A_mat[5,:] = [1]*3+[0]*2+[1]*2
A_mat[6,:] = [1]*4+[0]*2+[1]*1
A_mat.T

array([[1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1.],
       [1., 1., 1., 1., 1., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1., 1., 1.]])

In [97]:
for i in range(len(A_mat.T)):
    print(A_mat.T[i,:]  , sense_vec[i]  , b_vec[i])

[1. 0. 0. 1. 1. 1. 1.] > 5
[1. 1. 0. 0. 1. 1. 1.] > 13
[1. 1. 1. 0. 0. 1. 1.] > 12
[1. 1. 1. 1. 0. 0. 1.] > 10
[1. 1. 1. 1. 1. 0. 0.] > 14
[0. 1. 1. 1. 1. 1. 0.] > 8
[0. 0. 1. 1. 1. 1. 1.] > 6


In [98]:
#Gurobi
Mod = gp.Model()
Mod_x = Mod.addMVar(len(objective),vtype=['I']*len(objective))
Mod_con = Mod.addMConstrs(A_mat.T, Mod_x, sense_vec, b_vec)
Mod.setMObjective(None,objective,0,sense=gp.GRB.MINIMIZE)
Mod.Params.OutputFlag = 0 
Mod.optimize()

In [99]:
print(Mod.objval , Mod_x.x )

4830.0 [ 1.  8.  2. -0.  3.  1. -0.]
